shell="/opt/homebrew/bin/fish"

[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"
# just a maple mono italic
[font.italic]
family = "Maple Mono NF"
style = "Italic"
[font.bold_italic]
family = "Maple Mono NF"
style = "Bold Italic"

[window]
decorations = "Full"
dynamic_title = true
opacity = 1

[window.dimensions]
columns = 120
lines = 40


[keyboard]
[[keyboard.bindings]]
key = "Space"
mods = "Command|Shift"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "T"
mods = "Command"
# https://github.com/alacritty/alacritty/blob/63ef6c931901e895442edf5ec113d0ff609a7c24/alacritty.yml#L741
action = "ReceiveChar"
